-- ▀█▀ █▀█ █▀▀ █▀▀ █▀ █ ▀█▀ ▀█▀ █▀▀ █▀█
-- ░█░ █▀▄ ██▄ ██▄ ▄█ █ ░█░ ░█░ ██▄ █▀▄
-- Incremental Parsing

return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
		"nvim-treesitter/nvim-treesitter-context",
	},
	build = ":TSUpdate",
	event = { "bufreadpost", "bufnewfile" },
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			ignore_install = {},
			modules = {},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"c_sharp",
				"cairo",
				"cmake",
				"cpp",
				"css",
				"csv",
				"devicetree",
				"diff",
				"dockerfile",
				"editorconfig",
				"fsharp",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"graphql",
				"helm",
				"html",
				"http",
        "hyprlang",
				"javascript",
				"jq",
				"jsdoc",
				"json",
				"json5",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"nginx",
				"nix",
				"ocaml",
				"odin",
				"proto",
				"regex",
				"rasi",
				"robots",
				"rust",
				"sql",
				"ssh_config",
				"svelte",
				"swift",
				"tmux",
				"toml",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zig",
			},
		})

		require("treesitter-context").setup({
			max_lines = 3,
		})
	end,
}
