fork = false
frame = "full"
idle = true
maximized = false
neovim-bin = "/opt/homebrew/bin/nvim"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["DankMono Nerd Font"] # Will use the bundled Fira Code Nerd Font by default
size = 18.0
